<?php
if( function_exists('acf_add_local_field_group') ):

/**
 * OPTIONS GLOBALES DU THEME
 */

// activation des options
acf_add_local_field_group(array(
	'key' => 'group_5d6e44395feac',
	'title' => 'Theme informations',
	'fields' => array(
		array(
			'key' => 'field_5d6e446cc090d',
			'label' => 'ajout options',
			'name' => 'ajout_options',
			'type' => 'checkbox',
			'instructions' => 'Check options to show in theme administration options menu.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'contact' => 'Contact & Location',
				'reseaux' => 'Social networks',
				'partenaires' => 'Partners',
				'annuaire' => 'Directory',
				'calendar' => 'Calendar',
				'options'	=> 'Theme advanced option'
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-informations',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5d6e4d122e2c9',
	'title' => 'Directory Settings',
	'fields' => array(
		array(
			'key' => 'field_5ec2846a3a2d6',
			'label' => 'URL directory page',
			'name' => 'url_page_annuaire',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'page',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		),
		array(
			'key' => 'field_5d6e4d1d7d654',
			'label' => 'Link to directory',
			'name' => 'lien_annuaire',
			'type' => 'url',
			'instructions' => '(Insérer le lien vers l\'application d\'annuaire du laboratoire)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-annuaire',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5dadb18624429',
	'title' => 'Calendar Settings',
	'fields' => array(
		array(
			'key' => 'field_5dadb1927d6d8',
			'label' => 'URL Calendar',
			'name' => 'url_calendar',
			'type' => 'url',
			'instructions' => 'add link to page events list (might be https://website_url/events )',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-calendrier',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5d6e45131ccd4',
	'title' => 'Location Settings',
	'fields' => array(
		//TAB Location settings
		array(
			'key' => 'field_5ec283ff3a2d5',
			'label' => 'Link to Access page',
			'name' => 'url_page_access',
			'type' => 'page_link',
			'instructions' => 'Informations below will be shown in relation page',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'page',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		),
		array(
			'key' => 'field_5db6f28ec9561',
			'label' => 'Show on right shortcuts',
			'name' => 'display_map_shortcut',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5d95af7a91861',
			'label' => 'Informations',
			'name' => 'location_repeater',
			'type' => 'repeater',
			'instructions' => 'Enter address informations',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5d6e4556b87f7',
					'label' => 'Name of institute / laboratory',
					'name' => 'nom_laboratoire',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d6e457fb87f8',
					'label' => 'Postal Address',
					'name' => 'adresse',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 4,
					'new_lines' => 'br',
				),
				array(
					'key' => 'field_5d6e461b92f71',
					'label' => 'Contact name',
					'name' => 'contact_laboratoire',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d6e463092f72',
					'label' => 'Contact phone number',
					'name' => 'telephone_contact',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d88c18b0b677',
					'label' => 'Fax number',
					'name' => 'fax_contact',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d6e464492f73',
					'label' => 'Contact email',
					'name' => 'mail_contact',
					'type' => 'email',
					'instructions' => 'Saisir l\'adresse email du contact',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_5db6f2234981c',
					'label' => 'Show map',
					'name' => 'display_map',
					'type' => 'true_false',
					'instructions' => 'Souhaitez-vous afficher la carte ?',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'center_lat' => 53.5507112,
					'center_lng' => 10.0001335,
					'zoom' => 12,
					'key' => 'field_5d6e465a92f74',
					'label' => 'Map',
					'name' => 'map',
					'type' => 'open_street_map',
					'instructions' => 'Enter address here',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5db6f2234981c',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'osm',
					'layers' => array(
						0 => 'OpenStreetMap.HOT',
					),
					'allow_map_layers' => 1,
					'height' => 400,
					'max_markers' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-contact-et-localisation',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5d6e4c5dc9201',
	'title' => 'Social Settings',
	'fields' => array(
		array(
			'key' => 'field_5d6e4c78e8243',
			'label' => 'Social networks',
			'name' => 'reseaux_sociaux',
			'type' => 'repeater',
			'instructions' => 'Add social networks icons in footer area',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5d6e4c93e8244',
					'label' => 'Social networks link',
					'name' => 'lien_reseau_social',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-reseaux-sociaux',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

/**
 * COLORS
 * */
acf_add_local_field_group(array(
	'key' => 'group_5eff161ad0d6b',
	'title' => 'Colors',
	'fields' => array(
		array(
			'key' => 'field_5fae57bag7fe5',
			'label' => 'Complementary Colors',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		//TAB
		array(
			'key' => 'field_5efd9539079ff',
			'label' => 'Add color to theme palette',
			'name' => 'theme_palet_color',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => 'sedoo_color_repeater',
			),
			'collapsed' => '',
			'min' => 5,
			'max' => 5,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5efd959407a00',
					'label' => 'Color',
					'name' => 'added_theme_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
			),
		),
		array(
			'key' => 'field_5efeefd81e5d6',
			'label' => 'color palette managment ',
			'name' => 'mode_de_calcul',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => 'select_calcul_method',
			),
			'choices' => array(
				'triade' => 'Triade',
				'tetrade' => 'Tetrade',
				'analogic' => 'Analogic',
				'contrast' => 'Contraste',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5efedf57077bc',
			'label' => '',
			'name' => 'Regenerate',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => 'btn_regenerate_palette',
			),
			'choices' => array(
				'regenerer' => 'Regenerate',
			),
			'allow_null' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5fae57bah7fe5',
			'label' => 'Custom colors',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5eff103e6e8cc',
			'label' => 'Add custom colors',
			'name' => 'ajout_de_couleurs',
			'type' => 'repeater',
			'instructions' => 'Add here custom colors to use when editing content.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 5,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5eff104c6e8cd',
					'label' => 'Color',
					'name' => 'sedoo_select_custom_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
			),
		),
		array(
			'key' => 'field_5fae57bai7fe5',
			'label' => 'Messages colors',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5eff162073dc0',
			'label' => 'Green color',
			'name' => 'green_color',
			'type' => 'color_picker',
			'instructions' => 'Used for success messages.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#4caf50',
		),
		array(
			'key' => 'field_5eff164f73dc2',
			'label' => 'Orange color',
			'name' => 'orange_color',
			'type' => 'color_picker',
			'instructions' => 'Used for prevention messages.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ff9800',
		),
		array(
			'key' => 'field_5eff163f73dc1',
			'label' => 'Red color',
			'name' => 'red_color',
			'type' => 'color_picker',
			'instructions' => 'Used for warning messages.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#f44336',
		),
		array(
			'key' => 'field_5eff167973dc3',
			'label' => 'Blue color',
			'name' => 'blue_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#2196f3',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-theme-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

/** 
 * HEADER OPTIONS
 */

acf_add_local_field_group(array(
	'key' => 'group_5f11a0f3a031c',
	'title' => 'Header',
	'fields' => array(
		array(
			'key' => 'field_5fbc57bae7fe5',
			'label' => 'Header color',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5f6da2de5ac37',
			'label' => 'Header background appearance',
			'name' => 'sedoo_labs_header_appearance',
			'type' => 'select',
			'instructions' => 'Choose header appearance...',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'whiteHeader' => 'White (default)',
				'darkHeader' => 'Dark',
			),
			'default_value' => array(
				0 => 'whiteHeader:White (default)',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5fae57bae7fe5',
			'label' => 'Menu layout',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5f6da0eb5ac37',
			'label' => 'Main menu default layout',
			'name' => 'sedoo_labs_main_menu_layout',
			'type' => 'select',
			'instructions' => 'Choose default layout for menu...',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'grid' => 'Grid menu (default)',
				'flyout' => 'Flyout menu',
				'flyoutH' => 'Flyout menu horizontal level 2',
			),
			'default_value' => array(
				0 => 'grid:Grid menu',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5fae53436a4d1',
			'label' => 'Grid menu background color',
			'name' => 'sedoo_labs_grid_menu_color',
			'type' => 'select',
			'instructions' => '<a href="https://labo.obs-mip.fr/doc/category/header/" target="_blank">Documentation & examples</a> ',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f6da0eb5ac37',
						'operator' => '==',
						'value' => 'grid',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'whiteGrid' => 'White (default)',
				'coloredGrid' => 'Main theme color',
			),
			'default_value' => array(
				0 => 'whiteGrid:White',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5fae54c36a4d3',
			'label' => 'Grid menu columns',
			'name' => 'sedoo_labs_grid_menu_columns',
			'type' => 'range',
			'instructions' => 'How many columns for the grid menu ?
			<a href="https://labo.obs-mip.fr/doc/category/header/" target="_blank">Documentation & examples</a>',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f6da0eb5ac37',
						'operator' => '==',
						'value' => 'grid',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 5,
			'min' => 3,
			'max' => 6,
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_5fae57cde7fe6',
			'label' => 'Default feature image',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5f11a0f9c01a3',
			'label' => 'Default feature image ?',
			'name' => 'sedoo_img_defaut_yesno',
			'type' => 'true_false',
			'instructions' => 'If activated, every pages will have this default feature image as banner, if no feature image is defined explicitly.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5f11a17dc01a4',
			'label' => 'Choose image',
			'name' => 'sedoo_labs_default_cover_url',
			'type' => 'image',
			'instructions' => 'Format 1600*462 optimal.',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f11a0f9c01a3',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'cover',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-theme-options',
			),
		),
	),
	'menu_order' => 3,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

/**
 * FOOTER OPTIONS
 */
acf_add_local_field_group(array(
	'key' => 'group_5ebaa92f9edaf',
	'title' => 'Footer',
	'fields' => array(
		array(
			'key' => 'field_5ebab36e2427e',
			'label' => 'Images & colors',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5f1197056d8fc',
			'label' => 'Replace footer logo by another image ?',
			'name' => 'sedoo_labs_footer_replace_logo',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5f11972f6d8fd',
			'label' => 'Image',
			'name' => 'sedoo_labs_image_in_footer',
			'type' => 'image',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f1197056d8fc',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5f1197496d8fe',
			'label' => 'Link URL',
			'name' => 'sedoo_labs_footer_url_image',
			'type' => 'url',
			'instructions' => 'image not clickable is no link URL is defined',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5f1197056d8fc',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5ebaa93e884bd',
			'label' => 'Footer background SVG',
			'name' => 'footer_background_svg',
			'type' => 'image',
			'instructions' => 'Only SVG format allowed',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'svg',
		),
		array(
			'key' => 'field_5ebab3882427f',
			'label' => 'Footer color',
			'name' => 'footer_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#F2F2F2',
		),
		array(
			'key' => 'field_5ebac5bd14139',
			'label' => 'Footer text color',
			'name' => 'footer_text_color',
			'type' => 'color_picker',
			'instructions' => 'If you choose a colored background, please choose a light color for you typography.
Please refer to those <a href="https://material.io/design/color/text-legibility.html#text-types">Guide lines</a>.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#222222',
		),
		array(
			'key' => 'field_5ebabdc5e8c8d',
			'label' => 'Informations',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ebabdd6e8c8e',
			'label' => 'Show copyright',
			'name' => 'footer_show_copyright',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5ebabe69e8c8f',
			'label' => 'Copyright text',
			'name' => 'footer_copyright_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5ebabdd6e8c8e',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '© Copyright',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fbcbdc5e8c8d',
			'label' => 'Partners',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5d6e4cc5424e1',
			'label' => 'Partners',
			'name' => 'partenaires',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5d6e4ce0424e2',
					'label' => 'Link',
					'name' => 'lien_partenaire',
					'type' => 'url',
					'instructions' => 'Link to partner\'s website ',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d6e4cf4424e3',
					'label' => 'Logo',
					'name' => 'logo_partenaire',
					'type' => 'image',
					'instructions' => 'Upload partner\'s logo',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'full',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-theme-options',
			),
		),
	),
	'menu_order' => 4,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));


/**
 * SOURCE OF ARTICLE 
 * only for post (single.php)
 */

acf_add_local_field_group(array(
	'key' => 'group_5d6fb5f77ca9f',
	'title' => 'Post sources',
	'fields' => array(
		array(
			'key' => 'field_5d6fb628b251a',
			'label' => 'Sources',
			'name' => 'sources',
			'type' => 'textarea',
			'instructions' => 'Insert here post sources',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

/***
 * CHAMPS AUTEUR
 */
acf_add_local_field_group(array(
	'key' => 'group_5d6faffd00cb6',
	'title' => 'Author additionnal fields',
	'fields' => array(
		array(
			'key' => 'field_5d6fb014d56e1',
			'label' => 'Current position',
			'name' => 'poste',
			'type' => 'text',
			'instructions' => 'Provide your current position / poste dans l\'institution',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5d6fb025d56e2',
			'label' => 'Photo',
			'name' => 'photo_auteur',
			'type' => 'image',
			'instructions' => 'Upload your photo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'user_form',
				'operator' => '==',
				'value' => 'edit',
			),
		),
		array(
			array(
				'param' => 'user_form',
				'operator' => '==',
				'value' => 'register',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

/**
 * TABLE OF CONTENT
 */

acf_add_local_field_group(array(
	'key' => 'group_5d763c9864edf',
	'title' => 'Table of content',
	'fields' => array(
		array(
			'key' => 'field_5d763caf8246e',
			'label' => 'Table of content',
			'name' => 'table_content',
			'type' => 'checkbox',
			'instructions' => 'Show Table of content ?',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'toc' => 'Show',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'all',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'default',
			),
		),		
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5d6faf894c203',
	'title' => 'Select author',
	'fields' => array(
		array(
			'key' => 'field_5d6fafaccec98',
			'label' => 'Add author',
			'name' => 'ajouteur_auteur',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'interne' => 'Show local author (website\'s user)',
				'externe' => 'Insert external author',
			),
			'default_value' => array(
			),
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5d6fafcccec99',
			'label' => 'Select author',
			'name' => 'select_lauteur',
			'type' => 'user',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5d6fafaccec98',
						'operator' => '==',
						'value' => 'interne',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'role' => '',
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'array',
		),
		array(
			'key' => 'field_5d96f05c8037d',
			'label' => 'Photo external author',
			'name' => 'photo_auteur_exterieur',
			'type' => 'image',
			'instructions' => 'Upload photo',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5d6fafaccec98',
						'operator' => '==',
						'value' => 'externe',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5d96f0a18037e',
			'label' => 'External author name',
			'name' => 'nom_de_lauteur_exterieur',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5d6fafaccec98',
						'operator' => '==',
						'value' => 'externe',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5d96f0be8037f',
			'label' => 'External author position',
			'name' => 'poste_de_lauteur',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5d6fafaccec98',
						'operator' => '==',
						'value' => 'externe',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5d96f0fc80380',
			'label' => 'About author ',
			'name' => 'a_propos_auteur',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5d6fafaccec98',
						'operator' => '==',
						'value' => 'externe',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 4,
			'new_lines' => 'br',
		),
		array(
			'key' => 'field_5d96f13280381',
			'label' => 'Author\'s website ',
			'name' => 'site_internet_auteur',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5d6fafaccec98',
						'operator' => '==',
						'value' => 'externe',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'event',
			),
		),
		array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'tribe_events',
            ),
        ),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));


endif;
?>